
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Values.installation.namespace }}
  name: polaris-security-cluster-role
rules:
# TokenReview creation
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
{{ if .Values.polaris_security.signer }}
# Kubernetes CSR Usage ClusterRole when using another singer
- apiGroups:
    - certificates.k8s.io
  resources:
    - certificatesigningrequests
  verbs:
    - delete
    - deletecollection
    - get
    - put
    - list
    - create
- apiGroups:
    - certificates.k8s.io
  resources:
    - certificatesigningrequests/approval
  verbs:
    - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - {{ .Values.polaris_security.signer }}
  verbs:
  - approve
{{ end }}
---
# bind the role to polaris-security
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polaris-security-role-binding
  namespace: {{ .Values.installation.namespace }}
subjects:
- kind: ServiceAccount
  name: polaris-security # "name" is case sensitive
  namespace: {{ .Values.installation.namespace }}
roleRef:
  kind: ClusterRole
  name: polaris-security-cluster-role
  apiGroup: rbac.authorization.k8s.io
